# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RokuRemote < Formula
  desc "A CLI tool for managing Roku devices remotely"
  homepage "https://github.com/grahamplata/roku-remote"
  version "0.3.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/grahamplata/roku-remote/releases/download/v0.3.6/roku-remote_Darwin_x86_64.tar.gz"
      sha256 "bdbca64a82ba968e202277ac95a1cb301d0784a6d1c960487d71583ecb2060e2"

      def install
        bin.install "roku-remote"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/grahamplata/roku-remote/releases/download/v0.3.6/roku-remote_Darwin_arm64.tar.gz"
      sha256 "87869f7c3cec6726d38850f22b1c0e094f344d7663c9f0425c64cbb58f96a5c4"

      def install
        bin.install "roku-remote"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/grahamplata/roku-remote/releases/download/v0.3.6/roku-remote_Linux_x86_64.tar.gz"
      sha256 "04fff5a57bb7a8b4d2cb3255e6cfef96cc5e4512478f20a376c76010e436c419"
      def install
        bin.install "roku-remote"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/grahamplata/roku-remote/releases/download/v0.3.6/roku-remote_Linux_arm64.tar.gz"
      sha256 "56b51e8cb623eab8ea91e74b2160bad928518154f0a351bc3569b1f8dc6520cc"
      def install
        bin.install "roku-remote"
      end
    end
  end

  test do
    system "#{bin}/roku-remote --version"
  end
end
