# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RokuRemote < Formula
  desc "A CLI tool for managing Roku devices remotely"
  homepage "https://github.com/grahamplata/roku-remote"
  version "0.3.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/grahamplata/roku-remote/releases/download/v0.3.7/roku-remote_Darwin_x86_64.tar.gz"
      sha256 "166dc7924fdf2738a9330c85754673092f505ad9a4ef3d33ff7189f5784f9ec0"

      def install
        bin.install "roku-remote"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/grahamplata/roku-remote/releases/download/v0.3.7/roku-remote_Darwin_arm64.tar.gz"
      sha256 "6dd0104264d7de95956a2da9c2c0d272583d6480c29c67e600d9894a9dcda93b"

      def install
        bin.install "roku-remote"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/grahamplata/roku-remote/releases/download/v0.3.7/roku-remote_Linux_x86_64.tar.gz"
      sha256 "578360600281dfef7cee281e429e3bd37e0ee958d738ff8d01f9c3f955cdc2c5"
      def install
        bin.install "roku-remote"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/grahamplata/roku-remote/releases/download/v0.3.7/roku-remote_Linux_arm64.tar.gz"
      sha256 "05ee5b99481ec9acef82ab27377e16f5c933f5808179d67d934f0fb718e371aa"
      def install
        bin.install "roku-remote"
      end
    end
  end

  test do
    system "#{bin}/roku-remote --version"
  end
end
