# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RokuRemote < Formula
  desc "CLI tool for managing Roku devices remotely"
  homepage "https://github.com/grahamplata/roku-remote"
  version "0.3.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/grahamplata/roku-remote/releases/download/v0.3.5/roku-remote_Darwin_x86_64.tar.gz"
      sha256 "5a532341e0a37fd5ee9702ca6b0ecd44a3494ea684c8ff9a702ee35027b5164c"
    end
    if Hardware::CPU.arm?
      url "https://github.com/grahamplata/roku-remote/releases/download/v0.3.5/roku-remote_Darwin_arm64.tar.gz"
      sha256 "4ad78b9430257caec811cbca599b2e4e04c4fa010f30ad22b57aea2b1e71575b"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/grahamplata/roku-remote/releases/download/v0.3.5/roku-remote_Linux_x86_64.tar.gz"
      sha256 "523996e177605e186bba9517c77156ab942ae80d43888d9c2b4cdb9c8d0a13e6"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/grahamplata/roku-remote/releases/download/v0.3.5/roku-remote_Linux_arm64.tar.gz"
      sha256 "6d2cfaf41710edd9837f71893944675f794c1672949b83865f923749f933752a"
    end
  end

  def install
    bin.install "roku-remote"
  end

  test do
    system "#{bin}/roku-remote", "--version"
  end
end
